title: Avinash Gadde # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
text: Get to know me more
  <br><br>
  <a href="https://www.linkedin.com/in/avinashgadde/">LinkedIn</a> 
  <br>
  <a href="/images/Gadde, Avinash - Resume (2024).pdf?raw=true" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/acg425/">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
